### ISSUE TITLE
Support for .fromValue() constructor, and text parameter in standard constructor

### ISSUE THREAD

**Issue by TonyDowney** [micazi/rich_text_controller#1]
TextEditingController has two constructors:
`TextEditingController({ String text })`
and
`TextEditingController.fromValue(TextEditingValue value)`

As an extension of TextEditingController, the RichTextController should these two implemented.

**Comment by micazi** [comment]
Already worked it out in the new version!
Thank you for the contribution! 
Michael Aziz aka Micazi.
