### ISSUE TITLE
Not editable mentions support

### ISSUE THREAD

**Issue by radzish** [micazi/rich_text_controller#10]
This is rather question than issue. How/If it is possible to do so mentions themselves are not editable? So when user presses backspace (for example), whole mention is removed.

**Comment by micazi** [comment]
Thank you for the suggestion, I'm working on this feature.
If not in the 1.3.0 update, perhaps in the 1.4.0 one.
Thank you ;)

**Comment by micazi** [comment]
has been added in the 1.4.0 release, Check out the 'deleteOnBack' functionality!
Thank you!
