### ISSUE TITLE
Regex parsing fails if new values are added to the pattern map

### ISSUE THREAD

**Issue by BreSmit521** [micazi/rich_text_controller#11]
First off, great plugin, has been exactly what I'm looking for!  The issue I have is I want to make a pattern map that's dynamic

So, I start with something like:
```
final map = {RegExp('@') : TextStyle(fontWeight: FontWeight.bold)};

final controller = RichTextController(patternMap: map);
```

then later on I do something like: 
```
map['#'] =  TextStyle(fontWeight: FontWeight.bold);
```

This breaks all pattern matching but it does appear that the new pattern regex is propogated to the controller as expected, just no matches are returned.  Any thoughts on this or a potential workaround?  

Thanks again so much!

**Comment by BreSmit521** [comment]
After re-doing this from scratch it does seem to work with a valid map passed in but it would be nice if this accepted an empty map initially as well

**Comment by micazi** [comment]
Thank you for the contribution, would consider it in the next release :)

**Comment by micazi** [comment]
You will need to reInitiate the controller if you change maps, and you need to supply at least one nonempty map.
Thank you for your contribution!
