### ISSUE TITLE
Flutter 2.2.0 , Dart 2.13.0

### ISSUE THREAD

**Issue by joleth08** [micazi/rich_text_controller#14]
I got this error when I upgrade my flutter to 2.2.0, but when I run this package in 2.0.4 its running without error.

![image](https://user-images.githubusercontent.com/42792638/119953318-701d4000-bfd0-11eb-9dcd-98fae0bbd693.png)

this is my flutter doctor -v
```
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-PH)
    • Flutter version 2.2.0 at D:\flutter
    • Framework revision b22742018b (13 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Android
    • ANDROID_SDK_ROOT = D:\Android\cmdline-tools\tools
    • Java binary at: D:\Android\openjdk\bin\java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
    • All Android licenses accepted.
```

**Comment by joleth08** [comment]
Hi @micazi , 
I just add this line and save it and it works fine now.
![image](https://user-images.githubusercontent.com/42792638/119955012-2e8d9480-bfd2-11eb-85bf-5387a9b9fd7d.png)

**Comment by micazi** [comment]
Yes, This problem was already fixed in the latest commit.
Thank you!

**Comment by deucks** [comment]
Hi, I also have the same issue.     

> ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/rich_text_controller-1.3.0/lib/rich_text_controller.dart:38:12: Error: The method 'RichTextController.buildTextSpan' has fewer named arguments than those of overridden method 'TextEditingController.buildTextSpan'.
      TextSpan buildTextSpan({TextStyle? style, required bool withComposing}) {
               ^
    ../../Documents/flutter/packages/flutter/lib/src/widgets/editable_text.dart:192:12: Context: This is the overridden method ('buildTextSpan').
      TextSpan buildTextSpan({required BuildContext context, TextStyle? style , required bool withComposing}) {
               ^
    ../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/rich_text_controller-1.3.0/lib/rich_text_controller.dart:38:12: Error: The method 'RichTextController.buildTextSpan' doesn't have the named parameter 'context' of overridden method 'TextEditingController.buildTextSpan'.
      TextSpan buildTextSpan({TextStyle? style, required bool withComposing}) {


This is my flutter doc 

> [✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-AU)
    • Flutter version 2.2.3 at /Users/raajit/Documents/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/raajit/Library/Android/sdk
>     • Platform android-29, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 

I'm not sure how to go about this.
