### ISSUE TITLE
Add support for default composingStyle (TextDecoration.underline)

### ISSUE THREAD

**Issue by xsahil03x** [micazi/rich_text_controller#20]
The current implementation modifies the behavior and the currently composing text no longer shows the underline text-decoration.

Ideal implementation should merge both the default and passed styles.

**Comment by micazi** [comment]
I will look into it in the next release,
Thank you for your contribution. 😄

**Comment by micazi** [comment]
I can't really recreate this problem, Would you give me some snippets/previews to work on? 
```
TextFormField(
          controller: _controller,
          style: TextStyle(
            fontSize: 28,
            decoration: TextDecoration.underline,
          ),
        ),
```
This works for me and gives the modified size/underline decoration + my supplied regex style.
