### ISSUE TITLE
RegExp ignores multiline

### ISSUE THREAD

**Issue by JakesMD** [micazi/rich_text_controller#21]
Did [this issue](https://github.com/micazi/rich_text_controller/issues/6) ever get fixed? I need to be able to enable `multiline` in a RegExp but it just gets ignored.
```
myController = RichTextController(
  patternMatchMap: {
    RegExp(r'^#([a-zA-Z0-9]+)$', multiline: true): const TextStyle(color: Colors.blue),
  },
  onMatch: (List<String> matches) {},
);
```
So it formats it like this:
```
#Title [blue]
bla #title [not blue]
#Title foo baa [not blue]
```
At the moment my workaround is `'\n#([a-zA-Z0-9]+)\n'` but this can never match the first line of the TextField. So have to get around this by adding a TextInputFormatter that adds an empty line to the start of the TextField:
```
class MyFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
      TextEditingValue oldValue, TextEditingValue newValue) {
    return TextEditingValue(
      text: (!newValue.text.startsWith('\n') ? '\n' : '')+ newValue.text,
      selection: newValue.selection,
    );
  }
}
```

**Comment by micazi** [comment]
Hello, JakesMD!
Thank you for your contribution!
Great idea, I will be working on multiline functionality on the next version.
Hopefully in a couple of days.
Thanks!

Michael Aziz aka Micazi

**Comment by micazi** [comment]
I'm sorry I can't recreate this problem, 
Are you sure you are using correct regex patterns? 
this pattern does what you need (Highlight hashtags) -> \B#[a-zA-Z0-9]+\b
Don't forget to add the r"" so it becomes -> RegExp(r"\B#[a-zA-Z0-9]+\b")
keep in mind some regex modifiers don't work with flutter.
You can test your pattern in [https://regex101.com/] which is a very handy tool.
If there's anything else or your problem isn't solved, you're most welcome to open a new issue!
Thanks!
Michael W. Aziz aka Micazi
