### ISSUE TITLE
Bad State: no Element when using positive lookbehind

### ISSUE THREAD

**Issue by Sembauke** [micazi/rich_text_controller#25]
When using:
```Dart
    RegExp(r'(?<=(:)) .*', multiLine: true):  const TextStyle(color: Colors.blue),
```

With text value: 
```
color: blue;
```

It throws an error: Bad State no Element.

**Comment by sanidhya711** [comment]
Hey did you find a fix to this?

**Comment by Decron** [comment]
Hey Sembauke, bit of a long shot but do you remember how you fixed this? I am running into the same issue with a positive lookbehind and cannot find a solution.
