### ISSUE TITLE
patternMap.entries.singleWhere throws state error when multiple regexps match

### ISSUE THREAD

**Issue by TonyDowney** [micazi/rich_text_controller#3]
When the patternMap has two RegExp that both match the same String, this library throws a state error on `patternMap.entries.singleWhere`. I'd suggest replacing it with `firstWhere` and documenting the behaviour when multiple RegExp match.

**Comment by micazi** [comment]
Will work it out in the next version or if you'd like to fork and contribute i would highly appreciate it, Thank you! :smile:
