### ISSUE TITLE
stringMatchMap should have option to contain string or exact word match 

### ISSUE THREAD

**Issue by aiyubaarav** [micazi/rich_text_controller#35]
Example : 
For the text 'rainbon rainbontt' if i added string match map {rainbon : someStyle, rainbontt : : someStyle}
 - someStyle applied on rainbon only 
 When I debug on Match handler only comes to 1. rainbon not for rainbontt. So UI Look Like in screenshot
<img width="181" alt="Screenshot 2022-11-28 at 5 39 10 PM" src="https://user-images.githubusercontent.com/92848481/204274335-665bf9b1-8b83-42f4-9394-5561bf2a12fc.png">

@micazi 

For temporary solution i added space in regex :: 
<img width="740" alt="Screenshot 2022-11-28 at 5 40 15 PM" src="https://user-images.githubusercontent.com/92848481/204274514-806963eb-df9c-4321-8d52-4aefc4fbd79b.png">
RegExp(r'\b' + stringMatchMap!.keys.join(' |').toString() + r'+\b')

**Comment by micazi** [comment]
Thank you for your contribution, will look into it and integrate!
