### ISSUE TITLE
HOW - Dynamically add values to String Match Map

### ISSUE THREAD

**Issue by sakthimaheshalgo** [micazi/rich_text_controller#37]
How to dynamically add new entries to stringmatchmap during runtime? 
PS: Re-initializing the controller with new map throws controller has already been initialized error.

**Comment by micazi** [comment]
Currently there's no implementation for such thing, but will add this to my to-dos, adding a dynamic controller can be a nice enhancement. Thank you!

**Comment by micazi** [comment]
Closed and updated in version 2.0.0
Sorry, I haven't been active lately.
Thank you for your support!
