### ISSUE TITLE
String Match doesn't work when working with obscure mode.

### ISSUE THREAD

**Issue by danijorda1** [micazi/rich_text_controller#38]
TextField(
                  readOnly: true,
                  textAlign: TextAlign.center,
                  **obscureText: true,**
                  enableSuggestions: false,
                  autocorrect: false,
                  controller: _textEditingController,

**Comment by micazi** [comment]
Closed and updated in version 2.0.0
Sorry, I haven't been active lately.
Thank you for your support!
