### ISSUE TITLE
last item in stringMatchMap not work and fomat multiple string to one style

### ISSUE THREAD

**Issue by binhthanhk2** [micazi/rich_text_controller#40]
i have this line of code

 controller = RichTextController(
      stringMatchMap: {
        "test": const TextStyle(color: Colors.green),
        "bl": const TextStyle(color: Colors.red),
        "fu": const TextStyle(color: Colors.purple),
        "a": const TextStyle(color: Colors.white),
      },
      onMatch: (match) {},
      regExpMultiLine: true,
    );
    
    the last item of the stringMatchMap (in this case is 'a')  never work and do i have any options to style every StringMatchMap to a single Style ?

**Comment by GameTec-live** [comment]
i can confirm this issue, just makes the library annoying to use

**Comment by meet1691** [comment]
For a **temporary** solution, you can append one more string to the map of strings: TextStyle.
For example, append a full stop at the end along with the map.
...
stringMatchMap: {
"test": const TextStyle(color: Colors.green),
"bl": const TextStyle(color: Colors.red),
"fu": const TextStyle(color: Colors.purple),
"a": const TextStyle(color: Colors.white),
"." : const TextStyle(fontWeight: FontWeight.bold)
},

This will cover our last word- "a" .

**Comment by micazi** [comment]
Closed and updated in version 2.0.0
Sorry, I haven't been active lately.
Thank you for your support!
