### ISSUE TITLE
The following assertion was thrown building Builder:

### ISSUE THREAD

**Issue by hina06botify** [micazi/rich_text_controller#43]
The following assertion was thrown building Builder:
'package:rich_text_controller/rich_text_controller.dart': Failed assertion: line 71 pos 16: '(patternMatchMap != null && stringMatchMap == null) ||
            (patternMatchMap == null && stringMatchMap != null)': is not true.
            how can solve it

**Comment by micazi** [comment]
You have to provide either a 'patternMatchMap ' or a 'stringMatchMap' for the controller constructor.
