### ISSUE TITLE
Fork: Merge?

### ISSUE THREAD

**Issue by elana-voss** [micazi/rich_text_controller#45]
Thank you for the package!

I discovered that creating a single RegExp which splits the input tect creates problems for my use case. 

As I need individual RegExps (and Strings) that may or may not be case sensitive. 

I reworked the code to my needs. The changes are breaking and the code is very different. The README has been updated to reflect the new API and there is example code.

Please have a look:

https://github.com/xErik/rich_text_controller

**Comment by micazi** [comment]
Thank you so much for contributing, I will take a look into the code and see if it's possible to merge into the package, or if it would be better to publish your's as a standalone. in both cases, open-source community wins.
Thanks again for taking the time to refactor.
