### ISSUE TITLE
RegExp settings gets ignored (multiline, for example)

### ISSUE THREAD

**Issue by EriKWDev** [micazi/rich_text_controller#6]
Hi!
Since internally all regular expressions are combined as such:
```dart
allRegex = RegExp(patternMap.keys.map((e) => e.pattern).join('|'));
```
If any of the RegExp:s inside the map has something like multiline enabled, like ` RegExp(r"^\#+.*$", multiLine: true)`, those settings get discarded. It's a bit unclear that this is the behaviour since the map specifically maps RegExp objects to TextStyles. It would be clearer if the Map was between a String and the TextStyle.

However, I do think that having support for per-regex settings would be very nice so that last suggestion is a non-option xP

While it would make it a bit clunkier, I think we might have to loop over all regexes and check for each one separately... or at least combine the ones with similar settings.

**Comment by micazi** [comment]
Hello, Erik! 
First of all, Thank you for the contribution!, Really appreciate it.
Had an interest in what you have said about matching words not RegExp, So i added a new parameter in the controller to add a map of {String: TextStyle}. 
Notice that only one map can be given at a time!
The new version will be up in a few hours.
Thanks! 

Michael Aziz aka Micazi

**Comment by EriKWDev** [comment]
@micazi Well, I was kind of hoping that it wouldn't become a {String: TextStyle}.
I need to support multiline since I'm experimenting with syntax highlighting inside a multiline TextField. Would it not instead be better to keep the RegExp objects but actually utilize them?

**Comment by micazi** [comment]
They are already there and and i'm working on a solution!, 
Just added the string option as an extra :)

**Comment by EriKWDev** [comment]
Wonderful!
