### ISSUE TITLE
Update for recent changes to buildTextSpan

### ISSUE THREAD

**Issue by TimWhiting** [micazi/rich_text_controller#9]
Recently a breaking change landed in flutter master where buildTextSpan now has a BuildContext parameter passed to it, so that a custom TextController can use Colors from inherited widgets like Theme.

[here is the change](https://github.com/flutter/flutter/pull/73510/files)

I believe this is in flutter 2.0, correct me if I'm wrong, but it would be good to update to null-safety at the same time probably.
@micazi

**Comment by micazi** [comment]
Sorry for the long await. been swamped.
This bug has been resolved in the 1.3.0 update along with null safety :D  
and Thank you for your contribution ;)
